### ISSUE TITLE
Importing Menus

### ISSUE THREAD

**Issue by richtabor** [richtabor/MerlinWP#1]
I'd like for menus to also import as part of the content importer. That'd be awesome. 🙌

**Comment by andrastudio** [comment]
+1 from me

**Comment by aristath** [comment]
If I'm not mistaken they are part of the content xml export...

**Comment by richtabor** [comment]
I have it importing menu locations based on `get_theme_mod( 'nav_menu_locations' )` though that does not cover the actual pages/links within the menus. 🤔

**Comment by richtabor** [comment]
What do you think — should we specific menu navigation, or should that part specifically be left up to the user?

**Comment by JiveDig** [comment]
What ended up with this? I had to write my own function to set the menus to their locations. It seems to work, but feels like it should be part of MerlinWP core. Most of the time when importing demo content the user is going to want to import the menus as well IMO.

**Comment by richtabor** [comment]
@JiveDig How're you importing menus? I think it'd be a nice addition. Maybe even have a checkbox on the content importing view.

**Comment by JiveDig** [comment]
I went off your example file. It's based on slug so definitely not very useful in the core class. I just went off the main menu names we use in our demos and docs.
```
/**
 * Set the menus.
 *
 * @return  void
 */
add_action( 'merlin_after_all_import', function( $selected_import_index ) {

	$locations = $nav_menu_locations = array();

	// Get menus.
	$locations['header_left']  = maiconfigurations_get_menu_by_slug( 'header-left' );
	$locations['header_right'] = maiconfigurations_get_menu_by_slug( 'header-right' );
	$locations['primary']      = maiconfigurations_get_menu_by_slug( 'primary' );
	$locations['secondary']    = maiconfigurations_get_menu_by_slug( 'footer' );
	$locations['mobile']       = maiconfigurations_get_menu_by_slug( 'mobile' );

	// Loop through our nav menus.
	foreach ( $locations as $location => $menu ) {

		// Skip if no menu.
		if ( ! $menu ) {
			continue;
		}

		// Set as a valid menu.
		$nav_menu_locations[ $location ] = $menu->term_id;
	}

	// Bail if no menus.
	if ( ! $nav_menu_locations ) {
		return;
	}

	// Set the menus.
	set_theme_mod( 'nav_menu_locations', $nav_menu_locations );
});

function maiconfigurations_get_menu_by_slug( $slug ) {

	if ( $menu = get_term_by( 'slug', $slug, 'nav_menu' ) ) {
		return $menu;
	}

	if ( $menu = get_term_by( 'slug', $slug . '-nav', 'nav_menu' ) ) {
		return $menu;
	}

	if ( $menu = get_term_by( 'slug', $slug . '-menu', 'nav_menu' ) ) {
		return $menu;
	}

	return false;
}
```

There has to be a better way. Maybe storing/passing the menu object during import or something.

**Comment by JiveDig** [comment]
Also, this would be way more useful to do demo-specific stuff if we could get https://github.com/richtabor/MerlinWP/issues/120 data passed. I tried to re-architect the class a little but that one seems like you may want to have the first pass at it, if you agree and are motivated ;)

**Comment by richtabor** [comment]
> Also, this would be way more useful to do demo-specific stuff if we could get #120 data passed. I tried to re-architect the class a little but that one seems like you may want to have the first pass at it, if you agree and are motivated ;)

I honestly don't have a ton of resources currently for big parts here. 😅

**Comment by free3p** [comment]
How do I make the menu structure appear?
