### ISSUE TITLE
Installer wouldn't show up unless I switched themes

### ISSUE THREAD

**Issue by redlagoon** [richtabor/MerlinWP#101]
I've tried to get Merlin to work and I was in a swamp:

The logger said it displayed the setup, the option for "is theme already set up" wasn't there, yet the installer wouldn't show up.

So I de-activated the theme and re-activated it and now it works.

I've completed the setup, deleted the database entries for the options and the installer is not popping, as it should be, since I've already set-up, but what's a way to "refresh" the setup so that I can see the setup once again without having to re-activate the theme?

Is this intended?

**Comment by richtabor** [comment]
You can use `dev_mode` to keep the wizard active.

**Comment by richtabor** [comment]
You'll want to use the Reset WP plugin to reset and run through tests then. It makes it much easier.

**Comment by richtabor** [comment]
I updated the issue title to better describe the issue (if it's an issue). Please close if it's resolved via my comments.
