### ISSUE TITLE
TGMPA Issue (get_tgmpa_url)

### ISSUE THREAD

**Issue by JakeHenshall** [richtabor/MerlinWP#103]
Hi,

I'm trying to integrate MerlinWP into my theme.

I'm using MerlinWP from here -> MerlinWP/dist/merlin.zip

This is the Issue that I'm getting.

![tgmpa issue](https://user-images.githubusercontent.com/4720782/39156831-db16cb26-474f-11e8-82d7-495cae1e0fd6.jpg)

This is the line in question -> 
![tgmpa](https://user-images.githubusercontent.com/4720782/39156845-e71ea52e-474f-11e8-9354-140d9358efbe.png)

This is my folder structure for where both MerlinWP and TGMPA are located.

![tgmpa](https://user-images.githubusercontent.com/4720782/39156870-020cc21c-4750-11e8-925c-e8aff3995a89.jpg)

If I comment out Line 394, below is the issue. (Not sure if that helps in any way?)

![tgmpa issue 1](https://user-images.githubusercontent.com/4720782/39157001-9b5dbfb6-4750-11e8-8d79-adc8fe84ea5d.jpg)

Do I need to point MerlinWP to the inc/plugins/ directory, If so or not could you please point me in the right direction?

Thanks, Jake.

**Comment by capuderg** [comment]
Hi @JakeHenshall ,

this is from the main repository readme file:
> Also, if you have TGMPA included within your theme, ensure Merlin WP is included after it.

So, I think the issue is, that you are including/requiring the TGMPA after MerlinWP, and so the MerlinWP, does not have access to it.

Let me know, if that will solve your issue.

Take care!

**Comment by JakeHenshall** [comment]
@capuderg That's the badger, thanks mate, I just put the TGMPA files above MerlinWP and it works perfectly :).

Thanks, Jake.
