### ISSUE TITLE
Can I integrate multiple demos?

### ISSUE THREAD

**Issue by mdjwel** [richtabor/MerlinWP#108]
My theme has multiple demos. And I have to import those demos. Can I import multiple demos with MerlinWP?

Thanks in advanced.

**Comment by capuderg** [comment]
Hi,

sure you can. Take a look at the `merlin_import_files` filter in the example filters.php file: https://github.com/richtabor/MerlinWP/blob/master/merlin-filters-sample.php

Take care!
