### ISSUE TITLE
Disable default redirection on theme switch

### ISSUE THREAD

**Issue by aurora-hq** [richtabor/MerlinWP#113]
What would you suggest is the best way to disable the redirect on theme switch.
I see the action hook in the "class-metlin.php":
```php
add_action( 'after_switch_theme', array( $this, 'switch_theme' ) );
```
However, I'm having hard time accessing the "Merlin" class. Any tips on that? I don't think this is a Singleton class so I'm not sure what would be best to access it, I don't see any `get_instance()` or getter methods, so I'm stumped.
I did try things like:
```php
$merlin_instance = new Merlin();
remove_action( 'after_switch_theme', array( $merlin_instance, 'switch_theme' ) );
```
but that's not working.

Thx

**Comment by MrAndreius** [comment]
different instances of the class https://codex.wordpress.org/Function_Reference/remove_action
so it does not delete
try through the global $myclass;
remove_action( 'after_switch_theme', array( $myclass, 'my_action' ) );

if it does not help, then try again like this https://github.com/herewithme/wp-filters-extras/

**Comment by aurora-hq** [comment]
Thanks for the tips @MrAndreius 

Using the global $myclass variable will work only if the instance of "Merlin" class has been assigned to a variable. I looked through the entire code and could not find a single `new Merlin()` let alone assigned to a variable. According to Otto this is actually a bug: https://wordpress.stackexchange.com/a/36110

The filters extras functions work : https://github.com/herewithme/wp-filters-extras/blob/master/wp-filters-extras.php but don't you think it's a bit of a overkill to have to rely on bloated code functions which could potentially break over time as WP core changes to get simple things done. 
I think Merlin class should be fixed with either singleton or offer a a way to be accessed more readily, we're talking flexibility here right, being able to modify things if needed.

**Comment by aurora-hq** [comment]
Never mind, I found the Merlin class initiation, it's in the config file:
```
$wizard = new Merlin( ...
```
sorry, missed that earlier.
So, that solves the above, I can now access the global class instance and use it accordingly: 
```
remove_action( 'after_switch_theme', array( $GLOBALS['wizard'], 'switch_theme' ) );
```
or
```
global $wizard;
remove_action( 'after_switch_theme', array( $wizard, 'switch_theme' ) );
```
Might be a good idea to change that class variable in the config file to something more unique.
