### ISSUE TITLE
Import demo-content files

### ISSUE THREAD

**Issue by ange007** [richtabor/MerlinWP#114]
Hello.
How import remote demo-content files _(from **/upload/** dir)_?

**Comment by ange007** [comment]
As it turned out, Merlin downloads files by links. Thanks.

But it would not be bad to add the ability to use files from the archive.

**Comment by JiveDig** [comment]
I'm not sure I see the scenario where this would make sense. Can you explain it? If a theme is setting up the importer, they would be providing the files somehow. Requiring the user to first upload the file into WP (if that's what you mean) seems like an additional step that would just leave room for user-error in the process.

**Comment by ange007** [comment]
I meant downloading the archive from a remote server.
Or even when Demo content is distributed along with the theme.

**Comment by JiveDig** [comment]
My understanding is that it's already possible to do that, via the filter params here: 
https://github.com/richtabor/MerlinWP/blob/master/merlin-filters-sample.php#L105
```
'import_file_url' => 'https://www.example.com/merlin/demo-content.xml',
```

**Comment by ange007** [comment]
For this it is necessary because it was deployed demo?
And was the site always available?
This is not always possible.

**Comment by JiveDig** [comment]
This is what you were just trying to do though, right? Import demo content from a remote server.

**Comment by ange007** [comment]
Yes, and its work.
But I would like to be able to get demo content from the archive (remotely or locally).

**Comment by JiveDig** [comment]
I'm currently getting my demo file right from the plugin that runs merlin:
```
'local_import_file' => trailingslashit( MAI_CONFIGURATIONS_INCLUDES_DIR ) . 'demos/business/mai-business.xml',
```
Wherever you want to get it from, just put that url in there.

**Comment by ange007** [comment]
> Wherever you want to get it from, just put that url in there.

In the XML file there are direct links to the content. 
Which should be available. And for this need to place a demo server.

Similar is used in Unison framework.
http://manual.unyson.io/en/latest/extension/backups/

**Comment by JiveDig** [comment]
Right. That's how the XML importer in WP works. It won't be able to get images unless those images are actually available, which makes sense. It can't download an image that is not accessible.

**Comment by ange007** [comment]
> Right. That's how the XML importer in WP works. It won't be able to get images unless those images are actually available, which makes sense. It can't download an image that is not accessible.

That's why I'm talking about the possibility of working with the archive, and not with a remote server.

**Comment by JiveDig** [comment]
So you're not talking about pulling the xml file, but the actual content the xml file grabs? You could manually alter the xml file to grab the images from inside the theme or something. That would certainly be faster than downloading them offsite.
