### ISSUE TITLE
Not work "after_all_import_action"

### ISSUE THREAD

**Issue by ange007** [richtabor/MerlinWP#116]
Hello.

For some reason, the event "after_all_import_action" does not fire:
```php
	'install_callback' => array( $this->hooks, 'after_all_import_action' ),
```

Although this writing - everything is ok:
```php
	'install_callback' => function( ) { do_action( 'merlin_after_all_import', $selected_import_index ); },
```

What can be wrong?

**Comment by aurora-hq** [comment]
try using `merlin_after_all_import` hook instead.

**Comment by ange007** [comment]
`merlin_after_all_import` starts working only after the changes that I made.

**Comment by capuderg** [comment]
Hi,

there is an example at the bottom of this file: https://github.com/richtabor/MerlinWP/blob/master/merlin-filters-sample.php, which shows how to use the after import hook.

Take care!

**Comment by ange007** [comment]
Guess I did not correctly explain.
I use:
```php
add_action( 'merlin_after_all_import', function( )
{
	print_log('debug', 'merlin_after_all_import');
}
```

The whole day was spent for testing and debugging.
But the event did not work until I replaced the line in the merlin-class:
```php
'install_callback' => array( $this->hooks, 'after_all_import_action' ),
```
to
```php
'install_callback' => function( ) { do_action( 'merlin_after_all_import', $selected_import_index ); },
```

But...Today it all worked, when I changed it as it was ...
Very strange...
