### ISSUE TITLE
Widgets don't import because an option saves the number of registered widget areas first

### ISSUE THREAD

**Issue by JiveDig** [richtabor/MerlinWP#129]
My theme has an option for `footer_widget_count`. This successfully gets updated, but I think something needs to get "refreshed" for the theme code to then register the footer widget areas based on that value. I'm not sure if there is a way around this, but would love to understand how/why it doesn't work now.

To clarify:
1. My theme has a default of 2 footer widget areas.
2. Trying to import a demo that has the customizer option set to 4 footer widget areas.
3. The widgets DO import, they are just in the Inactive Widget section.
4. When i view the site after import there are 4 footer widget areas shown, but 3rd and 4th are missing their widgets (Inactive).

Any ideas what's going on?

**Comment by JiveDig** [comment]
Thanks, I tried that (and still do it). Turns out it's just a strange thing with my theme allowing the user to change the number of footer widgets. I have to pre-register the widget areas in order for it to work. Literally just got it to work this morning:
```
add_action( 'merlin_widget_importer_before_widgets_import', function( $data ) {

	// Disable existing widgets.
	update_option( 'sidebars_widgets', array() );

	$footer_widgets = 0;

	foreach ( $data as $id => $widgets ) {
		switch ( $id ) {
			case 'footer-1':
				$footer_widgets++;
				break;
			case 'footer-2':
				$footer_widgets++;
				break;
			case 'footer-3':
				$footer_widgets++;
				break;
			case 'footer-4':
				$footer_widgets++;
				break;
			case 'footer-5':
				$footer_widgets++;
				break;
			case 'footer-6':
				$footer_widgets++;
				break;
		}
	}

	// Make sure the theme supports the right amount of footer widgets.
	add_theme_support( 'genesis-footer-widgets', $footer_widgets );

	// Make sure all the footer widgets are registered.
	genesis_register_footer_widget_areas();

	// Set footer widget count option.
	genesis_update_settings( array(
		'footer_widget_count' => $footer_widgets,
	) );

});
```

**Comment by aurora-hq** [comment]
Cool, glad you found a solution!

**Comment by JiveDig** [comment]
This seems to be an issue with my specific solution so I'm closing the issue. Not something that Merlin needs to account for.
