### ISSUE TITLE
I want ignore step install plugin and create child theme when import

### ISSUE THREAD

**Issue by nguyenhungbk96** [richtabor/MerlinWP#142]
how to skip step install plugin and create child theme when importing. That is, select start and then enter

**Comment by JiveDig** [comment]
There is a filter on steps, dynamically created based on your theme name. I use Genesis and Merlin is for my child theme so I remove that step like this:
```
/**
 * Remove the child theme step.
 * This is for a Genesis child theme.
 *
 * @since   0.1.0
 *
 * @return  $array  The merlin import steps.
 */
add_filter( 'genesis_merlin_steps', function( $steps ) {
	unset( $steps['child'] );
	return $steps;
});
