### ISSUE TITLE
Not return home url when installed success

### ISSUE THREAD

**Issue by netbasejsc** [richtabor/MerlinWP#149]
[https://gyazo.com/d7c67139e05fd0a8a264a83d335c9a22](url)

When I installed success content, widget and ... , Merlin show message "All done. Have fun!" with button "Visit your website" but when I click this button he redirect yourself.

Thanks!

**Comment by Ninetheme** [comment]
same report https://d.pr/free/i/t00iVD

**Comment by richtabor** [comment]
> same report https://d.pr/free/i/t00iVD https://d.pr/free/i/7wbAHv

You need to add a url here: https://github.com/richtabor/MerlinWP/blob/master/merlin-config-sample.php#L35
