### ISSUE TITLE
Action/Filter prefix

### ISSUE THREAD

**Issue by meshakeeb** [richtabor/MerlinWP#15]
Hi,

You are using theme name as prefix for this it should be custom prefix which we can pass from config or it can be template name as If a theme has long name the prefix is too long which is not developer friendly.

so instead of `do_action( $this->theme . '_merlin_license_form' )` we can do is `do_action( $this->theme->template . '_merlin_license_form' )`

Thanks

**Comment by richtabor** [comment]
Thanks, I've made the change in the latest commit.
