### ISSUE TITLE
Next Button Issue

### ISSUE THREAD

**Issue by meshakeeb** [richtabor/MerlinWP#16]
Hi,

If the step is not successfully completed the button got disabled and not working.

Thanks

**Comment by richtabor** [comment]
Which screen are you referring to — or all?

**Comment by meshakeeb** [comment]
Plugin installation ...

**Comment by richtabor** [comment]
Is this within your branch? Sorry, I'm just trying to identify the issue and how to replicate it, so I can debug. 🐞

**Comment by meshakeeb** [comment]
Hi,

When any/all plugin return failed and not installed I am not unable to press install button again.

Thanks

**Comment by richtabor** [comment]
Hey @meshakeeb, are you still experiencing this issue with the latest build?

**Comment by richtabor** [comment]
Closed for inactivity, and I can't replicate the issue.
