### ISSUE TITLE
SVG illustrations are off in Chrome 

### ISSUE THREAD

**Issue by lumberman** [richtabor/MerlinWP#169]
Hey 👋🏼,

In Chrome SVG illustrations for each step have the wrong size. It can be fixed by removing width/height attributes. I will create a pull request for that.

### Before:

<img width="975" alt="Screen Shot 2019-05-14 at 2 56 16 PM" src="https://user-images.githubusercontent.com/1384471/57721067-a130af00-7659-11e9-8f82-0de2f8661d38.png">

### After:

<img width="975" alt="Screen Shot 2019-05-14 at 2 56 29 PM" src="https://user-images.githubusercontent.com/1384471/57721076-a8f05380-7659-11e9-9359-5febbc722a26.png">

**Comment by lumberman** [comment]
https://github.com/richtabor/MerlinWP/pull/170

**Comment by richtabor** [comment]
Nice!
