### ISSUE TITLE
Error with version bump 

### ISSUE THREAD

**Issue by NicholasKatsambiris** [richtabor/MerlinWP#17]
Looks like the latest version bump is missing single quotes around the version number.

Fatal error: syntax error, unexpected '.1' (T_DNUMBER) in /merlin/merlin.php on line 141

`if ( ! defined( 'MERLIN_VERSION' ) ) {
        define( 'MERLIN_VERSION', 1.0.1 );
}`

should be

`if ( ! defined( 'MERLIN_VERSION' ) ) {
        define( 'MERLIN_VERSION', '1.0.1' );
}`

**Comment by richtabor** [comment]
Thanks! Good catch. I see what happened now. I'll have a push here in a minute.
