### ISSUE TITLE
Content Selection to Import

### ISSUE THREAD

**Issue by meshakeeb** [richtabor/MerlinWP#18]
Hi,

Let the developer add multiple demos so user can select which demo he wants to import.

Thanks

**Comment by richtabor** [comment]
Definitely something to add eventually. 👍

**Comment by shakeeb-mts** [comment]
Hi,

![image](https://user-images.githubusercontent.com/22878349/30478749-bac8f2c6-9a2b-11e7-94cf-75bad79fe42f.png)

![image](https://user-images.githubusercontent.com/22878349/30478754-bfd921a0-9a2b-11e7-8d7f-0036c240507d.png)

Just complete the functionality.

Thanks

**Comment by primozcigler** [comment]
Hi @meshakeeb,

This option has been added in PR #43 and today I've published the release candidate, read more about it here: https://primoz.blog/pushing-merlin-wp-towards-stable-release/

@shakeeb-mts thanks for the screenshots, we'll discuss with @richtabor about the final UI. For now we have a <select> dropdown but this will be improved in the near future.
