### ISSUE TITLE
Template Files

### ISSUE THREAD

**Issue by meshakeeb** [richtabor/MerlinWP#19]
Hi,

Shouldn't we take out all the html out of merlin class and make template files easy to find and edit content.

Thanks

**Comment by richtabor** [comment]
I considered that, but don't you think things could easily get out of hand? I can't think of what extra HTML bits would need to be edited from a developers point-of-view really.

What's a use case scenario that you think would be appropriate?

**Comment by meshakeeb** [comment]
Hi,

Things are in control as I have done it in my fork version it make merlin.php file small also separation of view is good.

Also you aren't passing merling object to the body call of view so if any developer add any extra steps he is unable to access manything such as step_next_link, strings or other variables.

Thanks

**Comment by richtabor** [comment]
How do you suggest we do that?

**Comment by richtabor** [comment]
I'm going to close this as it's not a focus and the discussion as ceased. 👍
