### ISSUE TITLE
Page access

### ISSUE THREAD

**Issue by Fr4nkHorr1gan** [richtabor/MerlinWP#193]
Hello! I am having problems with Merlin after updating WordPress to version 5.3. When I try to activate a theme (I tried 7 themes that use this plugin), WordPress gives me a message about "Sorry, you are not allowed to access this page". What could be the matter, and how to fix it? Thanks.

**Comment by rupokify** [comment]
@Fr4nkHorr1gan Did you find anything in the debug log related to this?

**Comment by DistinctivePixels** [comment]
Seems related to a space in the URL - you should be able to access merlin via the WP admin link (Appearance > Theme Setup) - its just when the theme is activated and merlin tried to automatically forward to the setup page that its going wrong

Digging in now, hopefully not too tricky

**Comment by Fr4nkHorr1gan** [comment]
Thanks for the feedback. The fact is that 7 of my themes worked correctly with Merlin, but as soon as they updated to Wordpress 5.3, they immediately stopped functioning as i needed. I checked everything, in the end I had to disable the automatic launch of the installer, and now I start it manually.
