### ISSUE TITLE
Taxonomies are not assigned to Custom Post Types

### ISSUE THREAD

**Issue by richtabor** [richtabor/MerlinWP#21]

**Comment by shakeeb-mts** [comment]
@richtabor can you pass me some sample data I will test it

**Comment by richtabor** [comment]
The /york-pro/ demo within the package includes the sample data as well.

**Comment by primozcigler** [comment]
I believe that the OCDI code should fix this. I suggest we close the issue for now and it's reopened if needed, ok?
