### ISSUE TITLE
Several demos to choose from

### ISSUE THREAD

**Issue by heldervilela** [richtabor/MerlinWP#22]
Hi Rich,
Congratulations on the fantastic plugin.

Unfortunately for me, it does not serve because all my themes have more than one demo.

I believe that this is also the case for other authors.

Do you have any plans to add more than a demo available for the user to choose.?

**Comment by nicoandrade** [comment]
I think he answered here #18

**Comment by shakeeb-mts** [comment]
Hi,

![image](https://user-images.githubusercontent.com/22878349/30478749-bac8f2c6-9a2b-11e7-94cf-75bad79fe42f.png)

![image](https://user-images.githubusercontent.com/22878349/30478754-bfd921a0-9a2b-11e7-8d7f-0036c240507d.png)

Just complete the functionality.

Thanks
