### ISSUE TITLE
Plugin Wizard?

### ISSUE THREAD

**Issue by seb86** [richtabor/MerlinWP#24]
Can MerlinWP be used for setting up a plugin instead?

**Comment by shakeeb-mts** [comment]
Yes you can..

**Comment by seb86** [comment]
Can you explain a little more than that?

**Comment by shakeeb-mts** [comment]
What do you want to achieve with it define the steps and use it accordingly...

**Comment by seb86** [comment]
I would like the wizard to use jQuery Ajax to read a random single post and scan for specific elements on the page to see if they exist.

e.g. Main Container looking for ".site-main" or ".site-container"

If they do exist then for each element found a check is cleared. If any element is not found then the check is not cleared and the user is asked to look for those specific elements themselves using the browser developer tools.

**Comment by shakeeb-mts** [comment]
Hi,

You need to add steps using merlin_step filter and add a button with a callback something like this one:
https://github.com/richtabor/MerlinWP/blob/master/merlin.php#L906

And then write the callback functionality in JS like
https://github.com/richtabor/MerlinWP/blob/master/assets/js/merlin.js#L16

Thanks
