### ISSUE TITLE
Content doesn't import conletely

### ISSUE THREAD

**Issue by nicoandrade** [richtabor/MerlinWP#25]
When using the import demo content, pass without errors but the content is not imported completely.

I tested it with a content with 96 images but the images were placeholders and really small.
The plugin [One Click Demo Import](https://wordpress.org/plugins/one-click-demo-import/) uses [WP import 2.0](https://github.com/humanmade/WordPress-Importer) and works fine with all the XML Import Files I tested.

Maybe something like that can be implemented.

**Comment by richtabor** [comment]
Could you upload your theme zip with Merlin WP integrated so I can run some tests?

**Comment by primozcigler** [comment]
@nicoandrade the new importer from [OCDI plugin](https://wordpress.org/plugins/one-click-demo-import/) is now in use, can you give it a try again?

I'm closing this issue for now. If the issue persists, please reopen it and we'll take a further look.
