### ISSUE TITLE
Few issues based on Theme Review Guidelines

### ISSUE THREAD

**Issue by ernilambar** [richtabor/MerlinWP#32]
Here are few issues I found reviewing based on Theme Review guideline.

* PHP compatibility - Features from PHP 5.3 are used. Until WP core bumps the minimum PHP version, theme should run in PHP 5.2 also. If theme dont want to support PHP 5.2 then, there should be graceful failing and no PHP fatal errors.
* Child theme generator is plugin territory.
* Recommended plugin installation - I think there should be option to select/deselect plugins to install. It is not good to force users to `all plugins` or `no plugins`. Checkboxes would be good for each plugins in the list. All recommended plugins may not be necessary for a site.
* class-merlin-importer.php - WooCommerce pages are set by default. May be we need to make the Class more generic and provide some kind of filters so that theme can customize it.
* Redirection on theme activation - It is not allowed to redirect on theme activation. So, theme would need trigger URL to use in button. API to return Merlin URL would be great for returning such URL.

**Comment by richtabor** [comment]
All great points @ernilambar. 👍

**Comment by richtabor** [comment]
What would you suggest for the fourth point? 

A link as such: 
WP Dashboard > Appearance > Theme Wizard

**Comment by jb510** [comment]
PHP Compat:
Mark Jaquith just published a really nice graceful failing PHP version check https://gist.github.com/markjaquith/a08623974b37c2cf0207ee2b120b54da

Just my two cents (I've followed this project with _great_ interset for a while), but I see no reason to support pre-5.3 (actually I don't bother with pre-5.4 for new code/sites/themes). The 3% of WordPress sites still running 5.2 aren't installing new themes, and if they are now is the time they should upgrade. I personally feel the same about the 9% running 5.3, I have no qualms about pushing them to upgrade.

Child Themes:
FWIW, I hope to use this _for_ Genesis Child themes.

Plugin Installation:
Yes to checkboxes, but as a theme developer, I'd like to set some plugins to required and some optional.

**Comment by MrAndreius** [comment]
+ my cent
add the first step of verifying the version of WordPress
as it is done in Twenty Seventeen

**Comment by redlagoon** [comment]
@jb510 Way I see it, about 50% of our users (a big chunk) still use pre 7.0PHP.

There aren't many compatibility issues with PHP 5.6.x if you code for PHP 7.X, unless you use the new fancy things.

Many hosts are pushing PHP7 as of now and have one-click-setups to get it on your server. Unfortunately, Envato, as well as MOJO have been quite slow in adopting new changes from what I saw as well as talking to others.

Very good point. These users aren't buying any new themes, but it's a bit skewed to look at it this way. Envato would still be missing on ~34% of the market share (pre 5.5), which is just a crime.

So, from a business perspective, you need to hold on to these users.

**Comment by JiveDig** [comment]
As per using it in a child theme, I submitted this PR which would allow us to use in a child theme and a plugin. https://github.com/richtabor/MerlinWP/issues/118

**Comment by richtabor** [comment]
I've penned in time tomorrow morning to review the PR. Thanks @JiveDig !

**Comment by JiveDig** [comment]
@richtabor awesome thanks! LOVING Merlin so far. Also, this one could help a lot of us as well https://github.com/richtabor/MerlinWP/issues/120 (no PR though, but worth discussing)
