### ISSUE TITLE
Demo theme Bug (TGMPA integration)

### ISSUE THREAD

**Issue by maxviewup** [richtabor/MerlinWP#33]
I was trying to test the demo theme and i found an bug on it.

On path `york-pro/inc/admin/tgmpa/class-tgm-plugin-activation.php`  on line 2108, the function tests `function_exists( 'york-pro' )`  and if false, declare `function tgmpa(...) {...`.

What it should do is test if tgmpa exists.

The problem: 

If i have an plugin with TGMPA configured, it will try to redeclare the function and kill wordpress.

I've tried to find an repo for this theme to report this issue.

**Comment by richtabor** [comment]
Thanks for pointing this out. I've patched the theme itself and plan on removing the demo included here (as it's tough to maintain currently). 

Appreciate the heads up!
