### ISSUE TITLE
Feature Request: From $this->directory . '/merlin to $this->directory . '/

### ISSUE THREAD

**Issue by EnterpriseBranding** [richtabor/MerlinWP#34]
Hi. 

Just checking out Merlin (good name by the way since it is very magical like :D), which seems rather awesome and insightful of you as the Wordpress onboarding process, I agree lacks much actual "onboarding" from Wordpress itself and/or with the use of multiple other plugins.

In just getting started, I was hoping that the paths were a little more white labelish, meaning not needing to have the actual `merlin` directory in my theme. The wording of `merlin` is not consistent with my theme's folder naming. So all seems well with the very small adjustment in the screenshots below. 

Thought I would mention and suggest, if you feel fit for the context of your plugin. Thank you! And cheers to forward success of your magical like ideas and solutions. #Salute

![image](https://user-images.githubusercontent.com/6123260/33798652-a55802f4-dcea-11e7-80d9-864f5e14f475.png)

![image](https://user-images.githubusercontent.com/6123260/33798654-b083a20a-dcea-11e7-8b9c-9b66222a5f1f.png)

**Comment by richtabor** [comment]
Hey @FearlessMode!

Yea I get what you're saying, though it's necessary to have Merlin WP's contents within it's own directly. Maybe a better solution would be to have the folder name a setting within the configuration file? 

Although, without standardization, things could get messy if folks aren't aware of what files are from what packages. 

Just some thoughts!

**Comment by FearlessMode** [comment]
Hey @richtabor! 

Ok, sure. I see. 

Well it's up to you. Just a thought. 

Overall, It sounds like the option in the config would be ideal, because then the default would be the expected `/merlin` path, ultimately leaving it up to the dev to determine for their theme. 

For me, as of now or in the future I don't have an issue or complaint making the small adjustment.
