### ISSUE TITLE
Override Merlin_Helper class

### ISSUE THREAD

**Issue by tommusrhodus** [richtabor/MerlinWP#35]
Hey Rich,

Firstly, WOW, this is absolutely fantastic, great work!

**Issue:**

Wanting to override Merlin_Helper class to change texts without modifying /merlin/ contents in theme integration.

**Attempted:**

Copying Merlin_Helper class to functions.php and defining class before Merlin is included.

**Outcome:** 

Fatal Error: : Call to a member function helper_wizard() on a non-object in...

**Proposal**

merlin.php line 231:

`if ( ! class_exists( 'Merlin_Helper' ) and  true == $this->help_mode ) {`

Removing the class check here means that the class can be overridden by defining in functions.php before Merlin is included. Since the class check also takes place in includes/class-merlin-helper.php I'm thinking that the additional class check in the above is un-needed.

Cheers - Tom

**Comment by richtabor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merlin WP Issue #35](https://trello.com/c/mT4bzvQR/1667-merlin-wp-issue-35)

**Comment by richtabor** [comment]
Thanks Tom! Sounds good. I'll remove that. 👍
