### ISSUE TITLE
Feature Request: Redux Support & Importer Batch Processing

### ISSUE THREAD

**Issue by contempoinc** [richtabor/MerlinWP#38]
Would be awesome to add support for Redux along with batch processing the import into chunks to avoid server timeout issues, just like the new WordPress Importer V2 plugin handles everything.

https://github.com/humanmade/WordPress-Importer

More than willing to throw some funds into the project as I'm sure a bunch of other authors out there would be as well, make this the best damn theme onboarding process the community has ever seen!

**Comment by capuderg** [comment]
Hi @contempoinc 

The PR for the redux importer was just created: https://github.com/richtabor/MerlinWP/pull/47

@richtabor Will have to review and merge it to the master, before it's official.

@contempoinc Could you maybe test it out for us on "live" data? We don't use the Redux Framework in our themes, so I had to play/test with the sample data. It worked for me, but would like to get a conformation from theme authors, that actually use the Redux framework in their themes.

Take care!

**Comment by contempoinc** [comment]
@capuderg Sweet! I'll go ahead and test it out and get back to you tomorrow looks like @richtabor has already merged it into master as well.

**Comment by primozcigler** [comment]
Hey @contempoinc since this has been merged AFAIK tested by now, I'm closing the issue. However, if something's not working, reopen this issue and we'll take a look, ok?
