### ISSUE TITLE
Theme Check plugin WARNING

### ISSUE THREAD

**Issue by MrAndreius** [richtabor/MerlinWP#46]
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Skipping attachment "%s", fetching attachments disabled'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Cannot import auto-draft posts'
WARNING: file_put_contents was found in the file class-merlin-downloader.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 41: $saved_file = file_put_contents( $this->download_directory_path . $filename, $content );
WARNING: file_get_contents was found in the file class-merlin-widget-importer.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 69: $data = file_get_contents( $file );
WARNING: file_get_contents was found in the file class-merlin-customizer-importer.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 61: $raw = file_get_contents( $import_file_path );

**Comment by vlthemes** [comment]
Same issues.

**Comment by primozcigler** [comment]
@MrAndreius @vlthemes thanks for reporting. We'll check this before releasing v1 however I don't guarantee we'll fix these theme check warnings.

**Comment by vlthemes** [comment]
Thank you so much! Really great setup wizard.

Reviewers from themeforest will not miss such a warnings.

**Comment by vlthemes** [comment]
Also language folder is not used anywhere. *.pot file too.

It would be convenient if you used the same construction like here https://github.com/themegrill/flash/blob/master/inc/kirki/includes/class-kirki-l10n.php

Since only one text domain is allowed.

Screenshot:
http://take.ms/baHEp

**Comment by primozcigler** [comment]
@vlthemes are you ready to prepare a pull request to fix these issues? That's the best way and fastest way to push the project forward and ensure you can use it in your ThemeForest themes.

**Comment by vlthemes** [comment]
I`ll try to do this :)

**Comment by primozcigler** [comment]
That's amazing :rocket: 

I'll be more than happy to review it and merge it :+1:

**Comment by vlthemes** [comment]
Some errors in console log http://take.ms/PWAAA0

**Comment by primozcigler** [comment]
@vlthemes is this the same as #56?

**Comment by vlthemes** [comment]
Wow. Sorry :) Fixed

P. S. I commit Merlin in which some errors are fixed. It remains to decide the most important error.

**Comment by MrAndreius** [comment]
Guys, and you checked the code with the **themes check plugin** after adding a Monolog Logger?
In the same place, a bunch of errors are highlighted with which one will not miss a theme on the Envato

**Comment by scottparry** [comment]
You can close this issue. I've prevented Merlin from being checked by the Envato Theme Check plugin.

**Comment by scottparry** [comment]
Filename check within the Envato Theme Check plugin.

**Comment by MrAndreius** [comment]
@scottparry Thank you. This is great  (Evato was just an example)
@richtabor you closed the ticket, but how to be if the theme will be submitted on wordpress.com or .org and check here this plugin wordpress.org/plugins/theme-check
write Otto?

**Comment by richtabor** [comment]
@MrAndreius Merlin WP won't be allowed within themes bundled on .org. This type of functionality is frowned upon to exist within a theme itself. However, if we forked the wizard and made Merlin WP a plugin, it may be possible to include within the WordPress plugin directory.
