### ISSUE TITLE
EDD Software Licensing support

### ISSUE THREAD

**Issue by Kubitomakita** [richtabor/MerlinWP#48]
Hi,

do you plan to implement the integration with EDD SL? I mean the license activation and updating.

**Comment by primozcigler** [comment]
Hi,

Yes, it's planned. Tomorrow I'm publishing an exciting blog post about the advance of this project in the past month (spoiler alert: it's going out of beta *very* soon).

We'll need EDD SL integration in our upcoming theme so we'll be adding it for sure.

**Comment by primozcigler** [comment]
Hey, here is the announcement and you'll see that this issue is addressed in the blog post: https://primoz.blog/pushing-merlin-wp-towards-stable-release/

**Comment by Kubitomakita** [comment]
Thanks, already seen! :)

**Comment by capuderg** [comment]
Hi @Kubitomakita 

we've just merged a PR, which adds the EDD license activation steps. You can find more info here: https://github.com/richtabor/MerlinWP#4-easy-digital-downloads-license-activation-step

Could you please test it out and report any issues.

Thanks and take care!

**Comment by Kubitomakita** [comment]
Wow awesome, thanks!
