### ISSUE TITLE
Notice : ob_end_clean(): failed to delete buffer!

### ISSUE THREAD

**Issue by Ansif** [richtabor/MerlinWP#5]
Great ui/ux for installing themes and plugins smoothly! 💯 

In merlin installation page found this issue on wp_debug mode true.

Notice : ob_end_clean(): failed to delete buffer. No buffer to delete in /**/york-pro/inc/admin/merlin/merlin.php on line 351

Thanks! 👍

**Comment by rtthemes** [comment]
Got the same notice, in merlin.php on line 351 

Possible fix;

`if (ob_get_length()){
ob_end_clean();
}`

**Comment by richtabor** [comment]
Added in the latest bump to 1.0.1-beta. Thanks!
