### ISSUE TITLE
Selectively Check/Uncheck Plugins?

### ISSUE THREAD

**Issue by contempoinc** [richtabor/MerlinWP#50]
Someone might have already mentioned this but would be awesome to be able to selectively uncheck/check which plugins are to be installed (like everything else), other than ones that are required.

I also put together a little preview video for my buyers, sorry mic volume/gain was a little low on my Blue mic, this is using the Redux Framework option.

https://cl.ly/36040X2M182I

**Comment by primozcigler** [comment]
Hey @contempoinc 

Great video :+1: 

Yes, this has been already mentioned in issue #9 and PR #10 and I agree this would be cool to have. I'm  closing this issue so we don't have duplicates.
