### ISSUE TITLE
Setting Different Homepages and Slider Revolution for Multiple Demos?

### ISSUE THREAD

**Issue by contempoinc** [richtabor/MerlinWP#53]
Was looking through the filters and I see its possible to set "Home" or a custom page title as the front page, however, it would be nice to be able to set this on a per demo basis within the array, for example:

Adding the following:

import_home_page_title
import_slider_revolution

```
    array(
			'import_file_name'           => 'Vacation Rentals Slider',
			'import_file_url'            => 'http://www.your_domain.com/merlin/demo-content2.xml',
			'import_widget_file_url'     => 'http://www.your_domain.com/merlin/widgets2.json',
			'import_home_page_title' => 'Homepage Agent',
			'import_slider_revolution' => 'http://www.your_domain.com/merlin/listing-showcase.zip',
			'import_redux'               => array(
				array(
					'file_url'    => 'http://www.your_domain.com/merlin/redux_options2.json',
					'option_name' => 'redux_option_name2',
				),
			),
			'import_preview_image_url'   => 'http://contempothemes.com/wp-real-estate-7/multi-demo/wp-content/plugins/aqua-style-switcher/images/screenshots/vaca-slider-screenshot.jpg',
			'import_notice'              => __( 'A special note for this import.', 'your-textdomain' ),
			'preview_url'                => 'http://contempothemes.com/wp-real-estate-7/vacation-rentals-demo',
    ),

**Comment by contempoinc** [comment]
@primozcigler @capuderg @richtabor What do you think it would take to get this added? I'm more than willing to throw some money in for it.

**Comment by capuderg** [comment]
Hi @contempoinc,

this is already possible, but not yet documented (the documentation should be improved, that's for sure).

To import the revolution slider use the `import_rev_slider_file_url` or `local_import_rev_slider_file` pointing to the import zip file of the rev slider. I haven't tested the revolution slider importer yet, so let me know, if it works ok.

As for the home page setting, you can do that in the after import hook, where you can target the specific import (the parameter in this action hook/function is the index of the selected demo import, which is not shown in this code example): https://github.com/richtabor/MerlinWP/blob/master/merlin-filters.php#L189

**Comment by contempoinc** [comment]
@capuderg 

Awesome, to hear I'll test out the rev slider parameter.

In regards to specifying the index of the import for the homepage action I'm assuming you mean the index number in the array starting from 0, but do you have an example showing how this is done?

**Comment by MrAndreius** [comment]
`merlin_after_import_setup ($selected_import_index) {
if ( 'Demo 1' === $selected_import_index['import_file_name'] ) {
            // Assign menus to their locations.
            $main_menu = get_term_by( 'name', 'Main menu', 'nav_menu' );
            set_theme_mod( 'nav_menu_locations', array(
                    'primary' => $main_menu->term_id,
                )
            );
}elseif( 'Demo 2' === $selected_import_index['import_file_name'] ){
            // Set logo in customizer
            set_theme_mod( 'logo_img', get_template_directory_uri() . '/assets/images/logo1.png' );
}elseif( 'Demo 3' === $selected_import_index['import_file_name'] ){
            $social_links_menu = get_term_by( 'name', 'Social Menu', 'nav_menu' );
            set_theme_mod( 'nav_menu_locations', array(
                    'social' => $social_links_menu->term_id,
                )
            );
}
}`

**Comment by capuderg** [comment]
The above code is not correct...

As you said @contempoinc the index is a number of the selected import array starting from 0.

An example would be:

```
function merlin_after_import_setup( $selected_index ) {
	if ( 0 === $selected_index ) {
              // execute for first import only
        }

        // Execute for all imports
}
add_action( 'merlin_after_all_import', 'merlin_after_import_setup' );
``` 

Please try it out (I haven't tested it yet).

**Comment by contempoinc** [comment]
@capuderg Thank ya sir, I'll give that a shot and report back!

**Comment by contempoinc** [comment]
@capuderg Haven't tested this yet, still have to get all my content up on my server, set up a dev site, etc…but this is what you were referring to yeah?

    function merlin_after_import_setup( $selected_index ) {

	// Assign menus to their locations.
	$main_menu = get_term_by( 'name', 'Primary', 'nav_menu' );
	$footer_menu = get_term_by( 'name', 'Footer', 'nav_menu' );

	set_theme_mod( 'nav_menu_locations', array(
			'primary_left' => $main_menu->term_id,
			'primary_right' => $main_menu->term_id,
			'primary_full_width' => $main_menu->term_id,
			'footer' => $footer_menu->term_id,
		)
	);

	// Assign front page to specific imports
	if ( 7 === $selected_index ) {
	    $front_page_id = get_page_by_title( 'Homepage - Parallax' );
	    update_option( 'show_on_front', 'page' );
	    update_option( 'page_on_front', $front_page_id->ID );
        } elseif( 8 === $selected_index ){
	    $front_page_id = get_page_by_title( 'Agent Single Full Screen' );
	    update_option( 'show_on_front', 'page' );
	    update_option( 'page_on_front', $front_page_id->ID );
        } else {
    	    // Assign front page "Home" for the rest of the imports
	    $front_page_id = get_page_by_title( 'Home' );
	    update_option( 'show_on_front', 'page' );
	    update_option( 'page_on_front', $front_page_id->ID );
        }

    }
    add_action( 'merlin_after_all_import', 'merlin_after_import_setup' );

**Comment by capuderg** [comment]
@contempoinc yes, that should work.

**Comment by contempoinc** [comment]
@capuderg Everything worked great, however, the menu locations were set but are blank? I used the standard export process Tools > Export > All Content

**Comment by contempoinc** [comment]
Solved, and closed.

**Comment by ghost** [comment]
Import previously exported Revolution Slider sliders after demo import:

```
function merlin_after_import_sliders(  ) {
	if ( class_exists( 'RevSlider' ) ) {
		$sliders = glob( get_template_directory() . '/inc/revolution/sliders/*.zip' );
		if ( ! empty( $sliders ) ) {
			foreach ( $sliders as $slider_zip ) {
				$slider = new RevSlider();
				$slider->importSliderFromPost( true, true, $slider_zip );
			}
		}
	}
}
add_action( 'merlin_after_all_import', 'merlin_after_import_sliders' );
```
