### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of null at Object.ajax_callback [as success]

### ISSUE THREAD

**Issue by contempoinc** [richtabor/MerlinWP#56]
Assuming this is an issue with either timing out on execution as it has to do with the ajax callback?

![image](https://user-images.githubusercontent.com/686530/37048129-ce8dda60-2121-11e8-8416-3a4879cc2385.png)

**Comment by contempoinc** [comment]
I went back in and it seems everything imported but due to that error, it wouldn't process and let me continue to the final step? It just sat and spun forever.

**Comment by contempoinc** [comment]
@capuderg @primozcigler @richtabor Made a quick narrated video of the process and the error being thrown when a demo is selected and "Next" is clicked, the content does get imported however it never completes due to the JS error.

Screencast: https://cl.ly/2A2x2o3m1E0R

**Comment by contempoinc** [comment]
This is on a totally fresh install as well by the way.

**Comment by MrAndreius** [comment]
check the path to the files with the demo 
I had the same error if I tried to call local files as external
`'import_file_url'            => 'http://www.your_domain.com/merlin/demo-content.xml',`
`'local_import_file'            => trailingslashit( get_template_directory() ) . 'merlin/demo-content.xml',`
 here #45

**Comment by contempoinc** [comment]
Solved, and closed.
