### ISSUE TITLE
Can I use this filters (OCDI) in Merlin?

### ISSUE THREAD

**Issue by vlthemes** [richtabor/MerlinWP#60]
https://github.com/proteusthemes/one-click-demo-import/blob/master/docs/import-problems.md

**Comment by capuderg** [comment]
Which filter exactly do you want to use?

**Comment by vlthemes** [comment]
I want to use 2 filters from this page https://github.com/proteusthemes/one-click-demo-import/blob/master/docs/import-problems.md

**Comment by capuderg** [comment]
Hi,

you can use the `pt-importer/time_for_one_ajax_call` filter for changing the AJAX call length. And you can use the `merlin_regenerate_thumbnails_in_content_import` filter for disabling the thumbnails generation.

The use of those two filters are the same as on the page you linked.

Take care!
