### ISSUE TITLE
Plugins does`t activated

### ISSUE THREAD

**Issue by vlthemes** [richtabor/MerlinWP#63]
Plugins does`t activated, when the plugin is already installed but requires activation. Merlin misses the activation step.

For ex:

1) Add any plugin in TGMPA
2) Install it but not activate
3) Run Setup wizard

Plugins is not activated. I understand that Merlin works for a clean installation. Very often buyers change themes but plugins remain.

Check it please. Thank you!

**Comment by capuderg** [comment]
Hi,

I've just tested this on my test site and it works just OK. I've installed all needed plugins and a left them deactivated. Then I ran the wizard and all plugins activated successfully.

Could  you please try it out with the latest version of the WP Merlin: https://github.com/richtabor/MerlinWP/blob/master/dist/merlin.zip

I'll close this issue for now and it should be reopened, if other users have the same issue.
