### ISSUE TITLE
An error occurred during the usual installation of the plugin

### ISSUE THREAD

**Issue by MrAndreius** [richtabor/MerlinWP#64]
`Warning: call_user_func_array() expects parameter 1 to be a valid
callback, cannot access protected method Merlin::post_install_check() in
/wp-includes/class-wp-hook.php on
line 288`

How to repeat?
linux hosting, Apache, php7
Wordpress in multisite mode
open the plugin installation page
click add new
select plugin
click install
After installation, the activation screen for the network shows an error message

**Comment by capuderg** [comment]
Hi,

thanks for the bug report.

I'm not sure @richtabor, but this `post_install_check` is hooked into the `upgrader_post_install` hook and it resets the "merlin complete" option... The comment of the method says:

> After a theme update, we clear the slug_merlin_completed option...

Why would we need to clear the "merlin completed" option on theme update?

If this code is no longer needed, I would just remove it.

**Comment by MrAndreius** [comment]
probably @richtabor as an author, it is better to know whether this is necessary or not

**Comment by capuderg** [comment]
Yeah, the question was meant for @richtabor.

I've also go this PHP warning while installing the theme on my test hosting.

I would/will remove this, if there is no good reason for this code/hook.
