### ISSUE TITLE
Easy Digital Downloads Licence key not activate 

### ISSUE THREAD

**Issue by MrAndreius** [richtabor/MerlinWP#69]
key error returned
`This appears to be an invalid license key for.`
but, the key is working

screencast how it looks https://www.youtube.com/watch?v=8gzBlamwVP4

**Comment by capuderg** [comment]
Hi,

Could you please check the MerlinWP config file, I think some of the settings are not configured correctly. https://github.com/richtabor/MerlinWP/blob/master/merlin-config-sample.php

Maybe your 'edd_item_name' is missing or is not set to the EDD product name or maybe the slug is not correct?

Take care!

**Comment by MrAndreius** [comment]
oops
you are right, the edd_item_name was empty :( 
Thank you!!!
decided, can be closed
