### ISSUE TITLE
Remove the "theme" prefix from the license step

### ISSUE THREAD

**Issue by richtabor** [richtabor/MerlinWP#72]
@primozcigler I think having the "theme" prefix here is not necessary and keeps the wizard bound to themes only (looking into the future). As EDD licenses are for plugins and themes, I'd suggest that we remove the "theme" prefix from the license step/vars/everything. 
 
For example, `theme_license_step` and `theme-license`.

What do you think?

**Comment by capuderg** [comment]
Yeah, this can be done, no problem...

**Comment by primozcigler** [comment]
I agree. It's great to keep it as generic as possible in terms of using Merlin in themes/plugins or something completely else :+1:

**Comment by richtabor** [comment]
Resolved via PR #79. 👍
