### ISSUE TITLE
ZIP structure error

### ISSUE THREAD

**Issue by szepeviktor** [richtabor/MerlinWP#80]
@richtabor A WP plugin ZIP must have one directory in it and all files in that dir.

**Comment by richtabor** [comment]
Hi @szepeviktor, Merlin WP isn't a plugin. Is that what you're thinking, or are we on different pages here?

**Comment by szepeviktor** [comment]
Excuse me that is true.

But in README users are directed to copy files in `/inc/merlin/` so having a top directory will help them.
https://github.com/richtabor/MerlinWP#1-add-merlin-wp-to-your-theme

**Comment by szepeviktor** [comment]
I think the root of all these are:

- How developers of Merlin get&use Merlin (source)
- How Merlin users get&use Merlin (dist)
