### ISSUE TITLE
Example of a successfully implemented merlin_ajax_activate_license() filter

### ISSUE THREAD

**Issue by richtabor** [richtabor/MerlinWP#84]
Hey @capuderg, licensing looks great. 

There's just one bit I'm running into while trying to implement a filter for the license activation. Essentially, I have my theme license options setup a bit different, under one option, as such:  
<img width="806" alt="screen shot 2018-03-19 at 11 11 23 am" src="https://user-images.githubusercontent.com/1813435/37603971-4703b534-2b66-11e8-8acf-e0e8bee2a38d.png">

[Here's a gist](https://gist.github.com/richtabor/1ab3fecfc9241ba41f4949dc7067d75e#file-themebeans-license-php-L897-L1004) of what I'm trying to implement, though I'm running into a `TypeError: null is not an object (evaluating 'r.success')` JS error upon trying to activate a license.

Am I approaching this wrong? I'd appreciate any insights!

**Comment by richtabor** [comment]
Also, are you folks at ProteusThemes folks planning on running a filtered activation as well, or are you just using the standard _license_key and _license_key_status options?

**Comment by capuderg** [comment]
Hi @richtabor,

we are using a filtered activation and it's working OK. I would advise you to debug, what you get returned in the `r` in JS code. Maybe there is a PHP error in the filtered activation code and it does not return the correct response object.

Looking at your code, I don't see anything, that could cause that...

Take care!

**Comment by richtabor** [comment]
Thanks @capuderg — that's what I thought to. I couldn't find anything that would have caused the issue as well. Do you mind sending over a snippet of what you guys are doing?

**Comment by capuderg** [comment]
We are doing pretty much the same thing: create request data, send POST request to our website and process the results (with some minor changes)...

I think it's better, if we debug your code. Did you check what comes back to JS in the `r` variable?

**Comment by richtabor** [comment]
I just get the `TypeError: null is not an object (evaluating 'r.success')` JS error.

**Comment by capuderg** [comment]
I guess this error is reported on this line? https://github.com/richtabor/MerlinWP/blob/master/assets/js/merlin.js#L178

Do you have a Xdebug setup on your dev environment? Try debugging your filtered license activation code block by block and see, where it fails. If not, try to return the resulting array sooner ('success', 'message') to see which part breaks the execution.

**Comment by richtabor** [comment]
Thanks @capuderg, yea that looks like it. I don't. I'll take a look at it in the morning and see what I can uncover. 👍

**Comment by richtabor** [comment]
Figured out it! A stupid variable name mistake. 🤦‍♂️
