### ISSUE TITLE
Bug? call_user_func_array() expects parameter 1 to be a valid callback…

### ISSUE THREAD

**Issue by contempoinc** [richtabor/MerlinWP#89]
I have one person out of over 5400 getting this error below, he was running PHP 5.6.3 had him upgrade to 7 still the same thing. Nobody else is having the issue so I'm sure its some sort of server config problem, but anyone know what would cause this?

call_user_func_array() expects parameter 1 to be a valid callback, cannot access protected method Merlin::post_install_check() in /home/blackfin/public_html/nestwiser.com/wp-includes/class-wp-hook.php on line 288

**Comment by contempoinc** [comment]
This is in vendor > composer > ClassLoader.php > line 63

**Comment by capuderg** [comment]
This issue was already solved. Please use the latest version of the MerlinWP.

Reference: https://github.com/richtabor/MerlinWP/issues/64
