### ISSUE TITLE
"Not Allowed to Access this Page" even under Admin, sometimes?

### ISSUE THREAD

**Issue by contempoinc** [richtabor/MerlinWP#92]
I'm having some of my buyers get the "Not allowed to access this page" when trying to get to the theme setup, had 3 out of a couple hundred report it so its hit or miss, anyone else seeing this?

Screenshot: https://prnt.sc/j3hm2i

**Comment by contempoinc** [comment]
The user is admin level as well.

**Comment by contempoinc** [comment]
I've been just linking them this article https://premium.wpmudev.org/blog/fix-not-allowed-access-page-error-wordpress/ but wondering if anybody else has seen the same thing all their other admin level pages work fine.

**Comment by richtabor** [comment]
Hmm, are they trying to get to the wizard, after it's already been completed?

**Comment by contempoinc** [comment]
Waiting to hear back from one, but it seems that's the case. Does it get removed once the process has been completed I hadn't even noticed and not sure why they would try to access it again?

**Comment by richtabor** [comment]
Ah, I see. Currently, if you get to the last view, Merlin WP sets a option which removes the wizard at that point.

**Comment by richtabor** [comment]
You can back out at any point, but if you get to the last screen, it's removed.

**Comment by contempoinc** [comment]
Ah, gotcha that makes sense like I said out of almost a couple hundred only 3 have brought this up so its a really small use case, I can just let them know to do a reset if they didn't import — simple fix.
