### ISSUE TITLE
EDD License Tooltips with long text

### ISSUE THREAD

**Issue by ahmadsp10** [richtabor/MerlinWP#93]
![screenshot-tokopress-id-merlin dev cc-2018 04 11-15-41-16](https://user-images.githubusercontent.com/11994099/38605967-fe8cef3c-3d9e-11e8-8a37-8a7dbc491733.png)

**Comment by richtabor** [comment]
Yea, you should keep that tooltip content smaller if possible. The idea is that the ? icon gives you more information, or help if the text above isn't enough.
